### ISSUE TITLE
ДЗ 6

### ISSUE THREAD

**Issue by AndyAnderyan** [pavlena81/QAL-new-project#6]
### **Завдання 7**
```
- Встановіть всім елементаи li чорний текст і жовтий фон, крім елемента li з класом .first-item та останнього елемента li у списку
```
![image](https://github.com/pavlena81/QAL-new-project/assets/70598450/f503fec4-3e0b-432d-a9a7-aa765e82ba7a)
Ви виконали майже вірно, тоб то на таких даних воно працює як потрібно, але при зміні цих даних, правило буде порушено. Тому тут краще використати такий селектор:
```css
.ex_seven_list :not(.first-item):not(:last-of-type) {
   background: yellow;
   color: black;
}
```
